version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - mvn clean install
  build:
    commands:
      - mvn package
artifacts:
  files:
    - target/*.jar
    - scripts/*.sh
    - appspec.yml
  discard-paths: yes